# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contenu',
            field=models.TextField(null='Donc...'),
        ),
    ]
