# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170510_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contenu',
            field=models.TextField(null=True),
        ),
    ]
