# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170514_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de commentaire'),
        ),
    ]
