# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_date'),
        ('blog', '0004_auto_20170511_1240'),
    ]

    operations = [
    ]
