# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.AddField(
            model_name='comment',
            name='auteur_comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='auteur_comment', to='social.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='statut_comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='social.Statut'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date_commentaire'),
        ),
    ]
